- platform: aarlo
  monitored_conditions:
  - motion
  - sound
  - ding
  - cry
  - connectivity

#- platform: ffmpeg_motion
#  input: -rtsp_transport tcp -i rtsp://192.168.29.189:8964/front-porch-cam rtsp://192.168.29.189:8964/driveway-cam
#  name: FFMPEG Porch Motion
#  extra_arguments: -pred 1 -q:v 2
#  changes: 10
#  reset: 10

#- platform: ffmpeg_motion
#  input: -rtsp_transport tcp -i rtsp://192.168.29.189:8964/driveway-cam
#  name: FFMPEG Driveway Motion
#  extra_arguments: -pred 1 -q:v 2
#  changes: 10
#  reset: 10

#- platform: mqtt
#  unique_id: scrypted-driveway
#  device_class: motion
#  force_update: true
  

#- platform: mqtt
#  unique_id: shelly-6bb145awake
#  name: Bedroom Shelly HT Status
#  device_class: connectivity
#  enabled_by_default: true
#  device:
#    identifiers:
#      - master_bedroom_temp_sensor
#    manufacturer: Shelly
#    model: SH&T
#    name: Bedroom Temperature Sensor
#  force_update: true
#  state_topic: "shellies/shellyht-6BB145/online"
#  payload_on: "true"
#  payload_off: "false"
#  json_attributes_topic: "shellies/shellyht-6BB145/announce"
###  json_attributes_template: >
#    { "Shelly ID": "{{ value_json.id }}",
#      "Model": "{{ value_json.model }}",
#      "MAC": "{{ value_json.mac }}",
#      "IP Address": "{{ value_json.ip }}",
#      "Current Firmware": "{{ value_json.fw_ver }}",
#      "Update Available?": "{{ value_json.new_fw }}" }

#- platform: mqtt
#  name: Back Door MQTT Manual
#  unique_id: manual_mqtt_back_door
#  device_class: door
#  state_topic: zwave/kitchen/BackDoor/48/0/Any
#  value_template: '{{ value_json.value }}'
#  payload_on: true
#  payload_off: false
#  off_delay: 3
#  json_attributes_topic: zwave/kitchen/BackDoor/48/0/Any
#  json_attributes_template: >
#    {
#      "Last Updated": "{{ (value_json.time / 1000) | timestamp_local }}",
#      "Last Opened": "{{ states('input_datetime.back_door_last_opened_time') }}"
#    }

#- platform: mqtt
#  name: Garage Open or Close Notify MQTT
#  unique_id: mqtt_garage_notify_state
#  device_class: garage_door
#  state_topic: My_OpenGarage/OUT/NOTIFY
#  payload_on: "My OpenGarage just OPENED!"
#  payload_off: "My OpenGarage just CLOSED!"

#- platform: mqtt
#  name: Tanner Food Container Brown Sensor
#  unique_id: tanner_food_brown_opener
#  device_class: opening
#  device:
#    identifiers:
#      - tanner_food_sensor_brown
#    manufacturer: Ecolink
#    model: Z-Wave Door/Window Sensor (DWZWAVE25)
#    name: TannerFoodBrown
#    sw_version: '10.1'
#  payload_on: true
#  payload_off: false
#  off_delay: 3
#  value_template: '{{ value_json.value }}'
#  state_topic: zwave/TannerFoodBrown/48/0/Any
#  json_attributes_topic: zwave/TannerFoodBrown/48/0/Any
#  json_attributes_template: >
#    {
#      "Last Updated": "{{ (value_json.time / 1000) | timestamp_local }}"
#    }

#- platform: mqtt
#  name: Tanner Food Container White Sensor
#  unique_id: tanner_food_white_opener
#  device_class: opening
#  device:
#    identifiers:
#      - tanner_food_sensor_white
#    manufacturer: Ecolink
#    model: Z-Wave Door/Window Sensor (DWZWAVE25)
#    name: TannerFoodWhite
#    sw_version: '10.1'
#  payload_on: true
#  payload_off: false
#  off_delay: 3
#  value_template: '{{ value_json.value }}'
#  state_topic: zwave/TannerFoodWhite/48/0/Any
#  json_attributes_topic: zwave/TannerFoodWhite/48/0/Any
#  json_attributes_template: >
#    {
#      "Last Updated": "{{ (value_json.time / 1000) | timestamp_local }}"
#    }

#- platform: mqtt
#  unique_id: tannerwatermqtt
#  name: Tanner Water Manual MQTT
#  state_topic: "zwave/kitchen/TannerWaterBowl/48/0/Water"
#  json_attributes_topic: "zwave/kitchen/TannerWaterBowl/48/0/Water"
#  payload_on: true
#  payload_off: false
#  value_template: "{{ value_json.value }}"
#  device_class: moisture
#  enabled_by_default: false

#- platform: mqtt
#  unique_id: tannerwateralarmmqtt
#  name: Tanner Water Alarm Manual MQTT
#  state_topic: "zwave/kitchen/TannerWaterBowl/113/0/Water_Alarm/Sensor_status"
#  json_attributes_topic: "zwave/kitchen/TannerWaterBowl/113/0/Water_Alarm/Sensor_status"
#  payload_on: 2
#  payload_off: 0
#  value_template: "{{ value_json.value }}"
#  device_class: moisture
##  enabled_by_default: false

#- platform: template
#  sensors:


#    locksmatch:
#      friendly_name: Front Door Locks Match States
#      value_template: "{{ not is_state('lock.front_door', states('lock.august_asl_03_smart_lock_locked')) }}"
#      device_class: problem

#    homekitstarted:
#      friendly_name: "Homekit Running"
#      value_template: "{{ is_state('input_boolean.homekitstarted', 'on') }}"
#    nick:
#      friendly_name: Nick is Home
#      value_template: "{{ is_state('person.nick', 'home') }}"
#    darius:
#      friendly_name: Darius is Home
#      value_template: "{{ is_state('person.darius', 'home') }}"

- platform: ping
  host: !secret shelly_ip
  scan_interval: 15
  name: Shelly Ping Sensor