#- platform: aarlo

- platform: generic
  still_image_url: http://127.0.0.1:8123/local/snapshot_camera.porch_camera.jpg
#  stream_source: http://127.0.0.1:8123/local/10-10-2021_09-26-50.mp4
  name: Porch Motion Snapshot

- platform: generic
  still_image_url: http://127.0.0.1:8123/local/snapshot_camera.driveway.jpg
  name: Driveway Motion Snapshot

- platform: generic
  still_image_url: http://127.0.0.1:8123/local/snapshot_camera.back_deck.jpg
  name: Deck Motion Snapshot

#- platform: ffmpeg
#  input: -rtsp_transport tcp -i rtsp://192.168.29.189:8964/front-porch-cam
#  name: Porch Cam FFMPEG

#- platform: ffmpeg
#  input: -rtsp_transport tcp -i rtsp://192.168.29.189:8964/driveway-cam
#  name: Driveway Cam FFMPEG