- name: HassBridge
#  auto_start: true
  filter:
#    include_domains:
#     - climate
    include_entities:
     - binary_sensor.august_smart_lock_pro_3rd_gen_the_current_status_of_the_door
     - binary_sensor.caringaragestatus
     - climate.new_bedroom_thermostat
     - climate.downstairs_the_nest
     - fan.bonus_room_fan
     - fan.living_room_fan
     - fan.bedroom_fan2

     - input_boolean.caroline
     - input_boolean.nick
     - input_boolean.kara
     - input_boolean.darius

     - light.lamp
     - light.kitchen
     - light.driveway
     - light.porch
     - light.bedroom_light
     - light.living_room_ligh_living_room_light
     - light.hallway
     - light.under_bed_light
     - light.above_oven_light
     - light.above_cabinet_lights
     - light.under_cabinet_light
     - light.color_lights
     - light.bonus_room_light
     - light.desklamp

     - media_player.forked_daapd_output_shield
     - media_player.forked_daapd_output_office_apple_tv
     - media_player.forked_daapd_output_master_bedroom_apple_tv
     - media_player.forked_daapd_output_living_room_tcl_tv

     - person.nick
     - person.kara
     - person.darius

     - sensor.bonusroomtemp
     - sensor.shellytempfixed
     - sensor.nest_thermostat_temperature
     - sensor.dark_sky_temperature
     - sensor.dark_sky_apparent_temperature
     - sensor.dark_sky_precip_probability_0d
     - sensor.dark_sky_precip_probability_1d

     - switch.door
     - switch.idevices_switch
#     - switch.airplayserver_bathroom
#     - switch.airplayserver_deck
     - switch.bedroom_outlet_1
     - switch.bedroom_outlet_2
     - switch.bedroom_outlet_3
     - switch.master_bathroom_fan
     - switch.hassfrontporchspeaker
     - switch.tasmota_switch_1
     - switch.nick_s_pc
     - switch.office_tv_power
     - switch.receiver_outlet
     - vacuum.alfred
#     - person.michelle
#     - lock.august_asl_03_smart_lock_locked
#     - lock.front_door
#     - input_boolean.michelle
#     - media_player.living_room_remote
#     - cover.garage
#     - binary_sensor.garagedoorstatus
#     - camera.petcam
#     - input_boolean.4in1_first
#     - media_player.forked_daapd_output_receiver
#     - light.sonoff
#     - binary_sensor.back_door_mqtt_any
#     - light.zone2volume
#     - climate.master_bedroom_thermostat
#     - camera.bedroom_cam
#     - camera.tanner_cam
#     - climate.master_bedroom_thermostat_heat
#     - binary_sensor.back_door
#     - fan.bonus_room_fan
#     - fan.bonusfantemp
#     - switch.hassbathroomspeaker
#     - switch.hassz2
#     - switch.hassbackdeckspeaker
#     - media_player.bathroom_speaker
    exclude_entities:
     - media_player.onkyo
     - light.hue_go_1
     - light.hue_go_2
     - light.kitchen_nightlight
     - light.window_lamp
     - media_player.living_room_tv
     - media_player.onkyo_zone_2
     - switch.master_bath_speaker
     - switch.back_deck_speaker
     - switch.front_porch_speaker
     - light.porch
     - switch.driveway_lights
     - switch.playharmony
     - switch.pauseharmony
     - fan.bonus_room_fan_mqtt
     - device_tracker.nbauers_iphone
     - device_tracker.nbauers_iphone_2
     - switch.bonus_room_fan_action_switch
     - media_player.living_room_remote
    exclude_domains:
     - automation
     - binary_sensor
     - button
     - camera
     - climate
     - cover
     - device_tracker
     - fan
     - group
     - input_boolean
     - input_datetime
     - input_number
     - input_select
     - input_text
     - light
     - lock
     - media_player
     - person
     - remote
     - scene
     - script
     - select
     - sensor
     - switch
     - timer
     - vacuum
     - weather
     - zone
  entity_config:
    binary_sensor.caringaragestatus:
      name: Car in Garage
    binary_sensor.august_smart_lock_pro_3rd_gen_the_current_status_of_the_door:
      name: Front Door

    fan.living_room_fan:
      name: Living Room Fan
    fan.bedroom_fan:
      name: Master Bedroom Fan

    light.driveway:
      name: Driveway Lights
    light.bedroom_light:
      name: Master Bedroom Light
    light.hallway:
      name: Foyer Light
    light.living_room_ligh_living_room_light:
      name: Living Room Lights
    light.under_cabinet_light:
      name: Under Cabinet Light

    lock.august_asl_03_smart_lock_locked:
      name: Front Door Lock

    media_player.forked_daapd_output_shield:
      name: Shield Airplay Output
      feature_list:
       - feature: on_off
    media_player.forked_daapd_output_office_apple_tv:
      name: Garage Airplay Output
      feature_list:
       - feature: on_off
    media_player.forked_daapd_output_master_bedroom_apple_tv:
      name: Bedroom aTV Airplay Output
      feature_list:
       - feature: on_off
    media_player.forked_daapd_output_living_room_tcl_tv:
      name: TCL TV Airplay Output
      feature_list:
       - feature: on_off

    sensor.dark_sky_precip_probability_0d:
      name: Today
    sensor.dark_sky_precip_probability_1d:
      name: Tomorrow
    sensor.bonusroomtemp:
      name: Bonus Room Temperature
    sensor.nest_thermostat_temperature:
      name: Living Room Temperature
    sensor.dark_sky_temperature:
      name: Outdoors Temperature
    sensor.dark_sky_apparent_temperature:
      name: Outdoors feels like Temperature

    switch.tasmota_switch_1:
      name: Shower
      type: shower
    switch.hassfrontporchspeaker:
      name: Front Porch Speaker Switch
#    switch.airplayserver_bathroom:
#      name: Bathroom Airplay Output
#    switch.airplayserver_deck:
#      name: Back Deck Airplay Output
    switch.nick_pc:
      name: Nick's PC
    switch.office_tv_power:
      name: Bedroom TV
    switch.receiver_outlet:
      name: Receiver Outlet
      type: outlet

- name: Living Room Remote
  port: 59743
  mode: accessory
  filter:
    include_entities:
     - media_player.living_room_remote
  entity_config:
    media_player.living_room_remote:
      name: Living Room Remote
#      feature_list:
#       - feature: on_off
#       - feature: play_pause
#       - feature: toggle_mute
#- name: August Bridge
#  port: 51821
#  mode: accessory
#  filter:
#    include_entities:
#     - lock.front_door
#  entity_config:
#    lock.front_door:
#      name: Front Door Wifi
#      linked_battery_sensor: sensor.front_door_battery_template

#- name: SpeakerBridge
#  port: 51821
#  auto_start: true
#  filter:
#    include_entities:
#     - media_player.deck_speaker
#  entity_config:
#    media_player.deck_speaker:
#      name: Back Deck Speaker

#- name: HarmonyBridge
#  port: 51822
#  auto_start: true
#  filter:
#    include_entities:
#     - media_player.harmonytv
#  entity_config:
#    media_player.harmonytv:
#      name: Harmony Hub
#      feature_list:
#        - feature: on_off
#        - feature: play_pause
#        - feature: play_stop
#        - feature: toggle_mute