dreamscreen_main_source:
  alias: DreamScreen - Main Source
  sequence:
  - service: dreamscreen.set_hdmi_source
    data:
      fields:
        entity_id: dreamscreen.living_room
        source: 1
flash_bedroom_lights_purple:
  alias: Flash Bedroom Lamps Purple
  sequence:
  - data:
      entity_id: light.hue_go_1, light.hue_go_2
    service: light.turn_off
  - delay:
      milliseconds: 500
  - data:
      entity_id: light.hue_go_1, light.hue_go_2
      rgb_color:
      - 255
      - 0
      - 255
    service: light.turn_on
bathroom_speaker_media_player:
  alias: Turn On Bathroom Speaker and Ensure Back Deck Speaker is Off
  sequence:
  - service: switch.turn_on
    entity_id: switch.hassbathroomspeaker
  - service: media_player.turn_on
    data: {}
    entity_id: media_player.onkyo_zone_2
  - service: switch.turn_off
    entity_id: switch.hassbackdeckspeaker
    data: {}
  mode: single
backdeck_speaker_media_player:
  alias: Turn On Back Deck Speaker and Ensure Bathroom Speaker is Off
  sequence:
  - service: switch.turn_on
    entity_id: switch.hassbackdeckspeaker
  - service: media_player.turn_on
    data: {}
    entity_id: media_player.onkyo_zone_2
  - data: {}
    service: switch.turn_off
    entity_id: switch.hassbathroomspeaker
  mode: single
foyer_light_ten_min:
  alias: Turn on Foyer Light for 10 Minutes
  sequence:
  - data:
      brightness: 255
      entity_id: light.hallway
    service: light.turn_on
  - service: timer.start
    data: {}
    target:
      entity_id: timer.foyer_light_on
'1579731744650':
  alias: Bedroom Lights Off
  sequence:
  - entity_id: light.hue_go_1
    service: light.turn_off
  - entity_id: light.hue_go_2
    service: light.turn_off
  - type: turn_off
    device_id: 490ba522f9e011ea8bb3712c68a17879
    entity_id: light.under_bed_light
    domain: light
  - type: turn_off
    device_id: f16c40fb140e80d596d2e81eaedfd61b
    entity_id: light.bedroom_light
    domain: light
  - type: turn_off
    device_id: 26bd4341424620a80a8b14c1eecb55a7
    entity_id: light.kitchen_nightlight
    domain: light
  mode: single
'1579731898503':
  alias: Speakers Off
  sequence:
  - service: switch.turn_off
    target:
      entity_id: switch.airplayserver_bathroom
    data: {}
  - service: switch.turn_off
    target:
      entity_id: switch.airplayserver_deck
    data: {}
  - entity_id: switch.hassbackdeckspeaker
    service: switch.turn_off
  - entity_id: switch.hassbathroomspeaker
    service: switch.turn_off
  - entity_id: switch.hassfrontporchspeaker
    service: switch.turn_off
  - entity_id: switch.hassz2
    service: switch.turn_off
  - service: media_player.turn_off
    target:
      entity_id:
      - media_player.forked_daapd_output_master_bedroom_apple_tv
      - media_player.forked_daapd_output_shield
      - media_player.forked_daapd_output_receiver
    data: {}
  - service: media_player.turn_off
    target:
      entity_id:
      - media_player.forked_daapd_output_garage_apple_tv
    data: {}
    enabled: false
  mode: single
'1579732071901':
  alias: Inside House Lights Off
  sequence:
  - entity_id: light.kitchen
    service: light.turn_off
  - entity_id: light.hallway
    service: light.turn_off
  - entity_id: light.lamp
    service: light.turn_off
  - entity_id: light.living_room_ligh_living_room_light
    service: light.turn_off
  - entity_id: light.above_cabinet_lights
    service: light.turn_off
'1580158052666':
  alias: TV Volume Up 3x
  sequence:
  - data:
      command: VolumeUp
      device: '36419789'
    entity_id: remote.living_room
    service: remote.send_command
  - data:
      command: VolumeUp
      device: '36419789'
    entity_id: remote.living_room
    service: remote.send_command
  - data:
      command: VolumeUp
      device: '36419789'
    entity_id: remote.living_room
    service: remote.send_command
'1580158143285':
  alias: TV Volume Down 3x
  sequence:
  - data:
      command: VolumeDown
      device: '36419789'
    entity_id: remote.living_room
    service: remote.send_command
  - data:
      command: VolumeDown
      device: '36419789'
    entity_id: remote.living_room
    service: remote.send_command
  - data:
      command: VolumeDown
      device: '36419789'
    entity_id: remote.living_room
    service: remote.send_command
'1580584719238':
  alias: All Nick PC Outlets On
  sequence:
  - entity_id: switch.002006596001943c3b19_2
    service: switch.turn_on
  - entity_id: switch.002006596001943c3b19_3
    service: switch.turn_on
  - entity_id: switch.002006596001943c3b19_4
    service: switch.turn_on
restart_shield:
  alias: Restart Shield
  sequence:
  - service: androidtv.adb_command
    data:
      command: reboot
    entity_id: media_player.shield_adb
  mode: single
alexa_tts_bathroom:
  alias: Alexa TTS Bathroom
  sequence:
  - service: notify.alexa_media_bathroom_echo
    data:
      message: test fucking test
      data:
        type: tts
  mode: single
'1624664181825':
  sequence:
  - service: notify.alexa_media
    data_template:
      target: '{{ states(''input_select.alexa_message_target'') }}'
      data:
        type: announce
      message: '{{ states(''input_text.alexa_message_text'') }}'
  mode: single
  alias: Instant Message
living_room_play_pause:
  alias: Living Room Play_Pause
  sequence:
  - choose:
    - conditions:
      - condition: state
        entity_id: remote.living_room
        state: nvidia SHIELD
        attribute: current_activity
      sequence:
      - service: androidtv.adb_command
        data:
          entity_id: media_player.shield_adb
          command: sendevent /dev/input/event5 1 164 1 && sendevent /dev/input/event5
            0 0 0 && sendevent /dev/input/event5 1 164 0 && sendevent /dev/input/event5
            0 0 0
    - conditions:
      - condition: state
        entity_id: remote.living_room
        state: PowerOff
        attribute: current_activity
      sequence:
      - delay: ''
    default:
    - service: remote.send_command
      target:
        entity_id: remote.living_room_tcl_tv
      data:
        command: play_pause
  mode: parallel
  max: 10
living_room_rewind:
  alias: Living Room Rewind
  sequence:
  - choose:
    - conditions:
      - condition: state
        entity_id: remote.living_room
        state: nvidia SHIELD
        attribute: current_activity
      sequence:
      - service: androidtv.adb_command
        data:
          entity_id: media_player.shield_adb
          command: sendevent /dev/input/event5 1 168 1 && sendevent /dev/input/event5
            0 0 0 && sendevent /dev/input/event5 1 168 0 && sendevent /dev/input/event5
            0 0 0
    - conditions:
      - condition: state
        entity_id: remote.living_room
        state: PowerOff
        attribute: current_activity
      sequence:
      - delay: ''
    default:
    - service: remote.send_command
      target:
        entity_id: remote.living_room_tcl_tv
      data:
        command: reverse
  mode: parallel
  max: 10
living_room_fast_forward:
  alias: Living Room Fast Forward
  sequence:
  - choose:
    - conditions:
      - condition: state
        entity_id: remote.living_room
        state: nvidia SHIELD
        attribute: current_activity
      sequence:
      - service: androidtv.adb_command
        data:
          entity_id: media_player.shield_adb
          command: sendevent /dev/input/event5 1 208 1 && sendevent /dev/input/event5
            0 0 0 && sendevent /dev/input/event5 1 208 0 && sendevent /dev/input/event5
            0 0 0
    - conditions:
      - condition: state
        entity_id: remote.living_room
        state: PowerOff
        attribute: current_activity
      sequence:
      - delay: ''
    default:
    - service: remote.send_command
      target:
        entity_id: remote.living_room_tcl_tv
      data:
        command: forward
  mode: parallel
  max: 10
bedroom_lights_day:
  alias: Bedroom Lights Day
  sequence:
  - type: turn_on
    device_id: 490ba522f9e011ea8bb3712c68a17879
    entity_id: light.under_bed_light
    domain: light
    brightness_pct: 75
  - type: turn_on
    device_id: 26bd4341424620a80a8b14c1eecb55a7
    entity_id: light.kitchen_nightlight
    domain: light
    brightness_pct: 100
  mode: single
bedroom_lights_night:
  alias: Bedroom Lights Night
  sequence:
  - type: turn_on
    device_id: 490ba522f9e011ea8bb3712c68a17879
    entity_id: light.under_bed_light
    domain: light
    brightness_pct: 5
  - type: turn_on
    device_id: 26bd4341424620a80a8b14c1eecb55a7
    entity_id: light.kitchen_nightlight
    domain: light
    brightness_pct: 50
  - delay:
      hours: 0
      minutes: 0
      seconds: 1
      milliseconds: 0
  - data:
      brightness_pct: 100
      color_name: burlywood
    service: light.turn_on
    target:
      entity_id: light.hue_go_1
  - delay:
      hours: 0
      minutes: 0
      seconds: 1
      milliseconds: 0
  - data:
      brightness_pct: 100
      color_name: burlywood
    service: light.turn_on
    target:
      entity_id: light.hue_go_2
  mode: single
heat_switch_on:
  alias: Custom Thermostat - Heat Switch On
  sequence:
  - delay:
      hours: 0
      minutes: 0
      seconds: 10
      milliseconds: 0
  - service: climate.set_temperature
    target:
      entity_id: climate.downstairs_the_nest
    data:
      target_temp_high: '{{ states(''sensor.nest_thermostat_temperature'')|int(default=0)
        + 6}}'
      target_temp_low: '{{ states(''sensor.nest_thermostat_temperature'')|int(default=0)
        + 3}}'
  - delay:
      hours: 0
      minutes: 0
      seconds: 2
      milliseconds: 0
  - service: switch.turn_off
    data: {}
    target:
      entity_id: switch.nest_thermostat_fan
  mode: single
custom_thermostat_heat_switch_off:
  alias: Custom Thermostat - Heat Switch Off
  sequence:
  - service: climate.set_temperature
    target:
      entity_id: climate.downstairs_the_nest
    data:
      target_temp_high: '{{ state_attr(''climate.downstairs_the_nest'', ''target_temp_high'')
        }}'
      target_temp_low: '{{ states(''sensor.nest_thermostat_temperature'')|int(default=0)
        - 6}}'
  mode: single
custom_thermostat_ac_switch_on_duplicate:
  alias: Custom Thermostat - AC Switch On
  sequence:
  - service: climate.set_temperature
    data:
      target_temp_high: '{{ states(''sensor.nest_thermostat_temperature'')|int(default=0)
        - 3}}'
      target_temp_low: '{{ states(''sensor.nest_thermostat_temperature'')|int(default=0)
        - 6 }}'
    target:
      entity_id: climate.downstairs_the_nest
  - delay:
      hours: 0
      minutes: 0
      seconds: 2
      milliseconds: 0
  - service: switch.turn_on
    data: {}
    target:
      entity_id: switch.nest_thermostat_fan
    enabled: false
  mode: restart
custom_thermostat_ac_switch_off_duplicate:
  alias: Custom Thermostat - AC Switch Off
  sequence:
  - delay:
      hours: 0
      minutes: 0
      seconds: 2
      milliseconds: 0
  - service: climate.set_temperature
    target:
      entity_id: climate.downstairs_the_nest
    data:
      target_temp_high: '{{ states(''sensor.nest_thermostat_temperature'')|int(default=0)
        + 6}}'
      target_temp_low: '{{ state_attr(''climate.downstairs_the_nest'', ''target_temp_low'')
        }}'
  - service: switch.turn_off
    data: {}
    target:
      entity_id: switch.nest_thermostat_fan
    enabled: false
  mode: restart
custom_thermostat_discipline_nest:
  alias: Custom Thermostat - Discipline Nest if Heating or Cooling Improperly
  sequence:
  - choose:
    - conditions:
      - condition: state
        entity_id: climate.downstairs_the_nest
        attribute: hvac_action
        state: heating
      - condition: state
        entity_id: switch.bedroom_dummyheat
        state: 'off'
      sequence:
      - service: script.custom_thermostat_heat_switch_off
        data: {}
    - conditions:
      - condition: state
        entity_id: climate.downstairs_the_nest
        attribute: hvac_action
        state: cooling
      - condition: state
        entity_id: switch.bedroom_dummyac
        state: 'off'
      sequence:
      - service: script.custom_thermostat_ac_switch_off_duplicate
        data: {}
    default: []
    enabled: false
  mode: restart
custom_thermostat_update_set_temp:
  alias: Custom Thermostat - Update Set Temp
  sequence:
  - choose:
    - conditions:
      - condition: template
        value_template: '{{ (state_attr(''climate.downstairs_the_nest'', ''current_temperature'')|int(default=0)
          - (state_attr(''climate.downstairs_the_nest'', ''target_temp_low'')|int(default=0)))
          < 3 }}'
      - condition: state
        entity_id: switch.bedroom_dummyheat
        state: 'on'
      sequence:
      - service: climate.set_temperature
        target:
          entity_id: climate.downstairs_the_nest
        data:
          target_temp_high: '{{ states(''sensor.nest_thermostat_temperature'')|int(default=0)
            + 6}}'
          target_temp_low: '{{ states(''sensor.nest_thermostat_temperature'')|int(default=0)
            + 3}}'
    - conditions:
      - condition: template
        value_template: '{{ (state_attr(''climate.downstairs_the_nest'', ''target_temp_high'')|int(default=0)
          - (state_attr(''climate.downstairs_the_nest'', ''current_temperature'')|int(default=0)))
          < 3 }}'
      - condition: state
        entity_id: switch.bedroom_dummyac
        state: 'on'
      sequence:
      - service: climate.set_temperature
        target:
          entity_id: climate.downstairs_the_nest
        data:
          target_temp_high: '{{ states(''sensor.nest_thermostat_temperature'')|int(default=0)
            - 3}}'
          target_temp_low: '{{ states(''sensor.nest_thermostat_temperature'')|int(default=0)
            - 6}}'
    default:
    - service: script.custom_thermostat_discipline_nest
      data: {}
      enabled: false
  - choose:
    - conditions:
      - condition: state
        entity_id: switch.bedroom_dummyac
        state: 'on'
        for:
          hours: 0
          minutes: 0
          seconds: 30
      sequence:
      - delay:
          hours: 0
          minutes: 0
          seconds: 20
          milliseconds: 0
      - if:
        - condition: state
          entity_id: climate.downstairs_the_nest
          attribute: hvac_action
          state: idle
        then:
        - service: script.custom_thermostat_ac_switch_on_duplicate
          data: {}
    default: []
  mode: single
alfred_cleans_living_room_and_kitchen:
  alias: Alfred Cleans Living Room and Kitchen
  sequence:
  - service: vacuum.send_command
    data:
      command: '{ "command": "zoned_cleanup", "zone_ids": [ "Living Room and Kitchen"
        ] }'
    target:
      entity_id:
      - vacuum.alfred_re
  mode: single
alfred_cleans_from_card:
  alias: Alfred Cleans from Card
  description: Tells Alfred to clean a zone
  fields:
    cleaner:
      name: Vacuum
      description: The vacuum to clean with
      example: vacuum.rockrobo
      selector:
        text:
      default: ''
    zone_to_clean:
      name: Name of the zone
      description: The zone to clean
      example: Living Room and Kitchen
      selector:
        text:
      default: ''
    number_of_times_to_clean:
      name: Number of cleans
      description: How many times should the zone be cleaned (1-3)
      selector:
        number:
          min: 1
          max: 3
          step: 1
          mode: slider
      default: 1
  sequence:
  - service: vacuum.send_command
    data:
      command: '{ "command": "zoned_cleanup", "zone_ids": [ { "id": "{{ zone_to_clean|replace("[''",
        "")|replace("'']", "") }}", "repeats": {{ number_of_times_to_clean }} } ]
        }'
    target:
      entity_id: '{{ cleaner }}'
  mode: single
driveway:
  alias: Driveway Motion Off
  sequence:
  - service: mqtt.publish
    data:
      topic: wyzehksv/driveway/motion/OFF
      payload: '{ "on":false }'
  - service: switch.turn_off
    data: {}
    target:
      entity_id: switch.driveway
  mode: single
alfred_cleans_living_room_and_kitchen_2:
  alias: Alfred Cleans Living Room and Kitchen Valetudo
  sequence:
  - service: mqtt.publish
    data:
      topic: valetudo/valetudorockrobo/ZoneCleaningCapability/start/set
      payload: 0bedfb06-c3bc-4427-98a2-fd52a556c309
  mode: single
alfred_butters_defense:
  alias: Alfred Butters Defense Valetudo
  sequence:
  - service: mqtt.publish
    data:
      topic: valetudo/valetudorockrobo/ZoneCleaningCapability/start/set
      payload: a034ef9c-5a6f-41af-9abb-b9330d1c65d8
  mode: single
alfred_butters_defense_re:
  alias: Alfred Butters Defense RE
  sequence:
  - service: vacuum.send_command
    data:
      command: '{ "command": "zoned_cleanup", "zone_ids": [ "Butters Defense" ] }'
    target:
      entity_id:
      - vacuum.alfred_re
  - delay:
      hours: 0
      minutes: 0
      seconds: 1
      milliseconds: 0
  - service: vacuum.set_fan_speed
    data:
      fan_speed: min
    target:
      entity_id: vacuum.alfred_re
  mode: single
frigate_snapshots:
  alias: Frigate snapshots
  sequence:
  - service: camera.snapshot
    data:
      filename: /config/www/frigate_driveway.jpg
    target:
      entity_id:
      - camera.driveway
    enabled: false
  - service: camera.snapshot
    data:
      filename: /config/www/frigate_camera.back_deck.jpg
    target:
      entity_id: camera.back_deck
    enabled: false
  - service: camera.snapshot
    data:
      filename: /config/www/driveway-cam.jpg
    target:
      entity_id: camera.driveway_scrypted
  - service: camera.snapshot
    data:
      filename: /config/www/back-deck-cam.jpg
    target:
      entity_id: camera.scryp_back_deck
  - service: camera.snapshot
    data:
      filename: /config/www/front-porch-cam.jpg
    target:
      entity_id: camera.front_deck_scrypted
  mode: parallel
  max: 3
garage_automations_off:
  alias: Garage Automations Off
  sequence:
  - service: automation.turn_off
    data: {}
    target:
      entity_id:
      - automation.welcome_home_nick_garage
      - automation.zpresence_welcome_home_caroline_garage
      - automation.welcome_home_kara_garage
      - automation.zpresence_welcome_home_brandon_garage
      - automation.zpresence_welcome_home_carlee_garage
  mode: single
garage_automations_on:
  alias: Garage Automations On
  sequence:
  - service: automation.turn_on
    data: {}
    target:
      entity_id:
      - automation.welcome_home_nick_garage
      - automation.zpresence_welcome_home_caroline_garage
      - automation.welcome_home_kara_garage
      - automation.zpresence_welcome_home_brandon_garage
      - automation.zpresence_welcome_home_carlee_garage
  mode: single
