esphome:
  name: bedroomfanswitch
  platform: ESP8266
  board: esp01_1m

uart:
  rx_pin: GPIO3
  tx_pin: GPIO1
  baud_rate: 115200

# Enable logging
logger:
  baud_rate: 0

# Enable Home Assistant API
api:
#  encryption:
#    key: 03dWSoBo3/skXpNR1LIvEIgJy5ZvtfmYpQhO3Xu40+4=

ota:
  password: "9e88767254488c7cac99b0f2063ca2b9"

wifi:
  ssid: !secret wifi24g_ssid
  password: !secret wifi24g_pass

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Treatfan-7828 Fallback Hotspot"
    password: "0vqOp6G8qtRx"

captive_portal:

tuya:

web_server:
  port: 80

text_sensor:
# Expose ESPHome version as sensor.
  - platform: version
    name: Bedroom Fan-Light ESPHome Version
    
  - platform: wifi_info
    ip_address:
      name: Bedroom Fan-Light IP Address
    ssid:
      name: Bedroom Fan-Light SSID
    bssid:
      name: Bedroom Fan-Light BSSID

sensor:
  - platform: wifi_signal
    name:  Bedroom Fan-Light Wifi Signal
    update_interval: 60s
    filters:
      - delta: 0.01
      - throttle: 300s

  - platform: uptime
    name: Bedroom Fan-Light uptime
    filters:
      - throttle: 300s

light:
  - platform: "tuya"
    name: Bedroom Light
    dimmer_datapoint: 10
    switch_datapoint: 9
    min_value: 100
    max_value: 1000

fan:
  - platform: "tuya"
    name: Bedroom Fan
    switch_datapoint: 1
    speed_datapoint: 3
    speed_count: 4
